### ISSUE TITLE
Run gulp in engine folder failed.

### ISSUE THREAD

**Issue by SchumyHao** [ioBroker/ioBroker.docs#164]
I cloned the repo.
run `npm i` in engine folder
run `gulp` failed.
```
gulp
[13:51:25] Using gulpfile ~/git/ioBroker.docs/engine/gulpfile.js
[13:51:25] Starting 'default'...
[13:51:25] Starting '0.clean'...
[13:51:25] Finished '0.clean' after 2.48 ms
[13:51:25] Starting '1.blog'...
(node:47951) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (fs.js:750:3)
    at parts.forEach.part (/home/schumy/git/ioBroker.docs/engine/build-lib/utils.js:110:46)
    at Array.forEach (<anonymous>)
    at createDir (/home/schumy/git/ioBroker.docs/engine/build-lib/utils.js:108:11)
    at Object.writeSafe (/home/schumy/git/ioBroker.docs/engine/build-lib/utils.js:118:5)
    at fs.readdirSync.forEach.item (/home/schumy/git/ioBroker.docs/engine/build-lib/blog.js:80:27)
    at Array.forEach (<anonymous>)
    at resolve (/home/schumy/git/ioBroker.docs/engine/build-lib/blog.js:13:52)
    at new Promise (<anonymous>)
    at build (/home/schumy/git/ioBroker.docs/engine/build-lib/blog.js:9:12)
(node:47951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:47951) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[13:51:25] The following tasks did not complete: default, 1.blog
[13:51:25] Did you forget to signal async completion?
```

I tired on OSX Linux, both failed.
Only success on Windows PC.

**Comment by SchumyHao** [comment]
This maybe caused by the root path with **/**home/schumy/git/ioBroker.docs/engine/build-lib/utils.js


This will be replaces in `engine/build-lib/utils.js` `function writeSafe(fileName, data)`  `const parts = fileName.replace(/\\/g, '/').split('/');` and become to ""
