### ISSUE TITLE
[Bug]: < > in copyright string crashes site

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.docs#386]
### Contact Details

jey-cee@live.com

### What happened?

If the copyright string has < > in it like on heatingcontrol readme <2019-2021>, they can't be opened while it crashes.
Click on the link to see only a white page. 
In the browser console is a message that says "The tag name provided ('2019-2021') is not a valid name." here we see the copyright year string.

### Link

https://www.iobroker.net/#de/adapters/adapterref/iobroker.heatingcontrol/README.md

### Relevant log output

```shell
Uncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('2019-2021') is not a valid name.
    at Za (https://www.iobroker.net/static/js/2.fa83f41b.chunk.js:2:823778)
    at cl (https://www.iobroker.net/static/js/2.fa83f41b.chunk.js:2:845141)
    at ul (https://www.iobroker.net/static/js/2.fa83f41b.chunk.js:2:845029)
    at sl (https://www.iobroker.net/static/js/2.fa83f41b.chunk.js:2:844882)
    at Js (https://www.iobroker.net/static/js/2.fa83f41b.chunk.js:2:841891)
    at https://www.iobroker.net/static/js/2.fa83f41b.chunk.js:2:793276
    at t.unstable_runWithPriority (https://www.iobroker.net/static/js/2.fa83f41b.chunk.js:2:868857)
    at Hi (https://www.iobroker.net/static/js/2.fa83f41b.chunk.js:2:792985)
    at qi (https://www.iobroker.net/static/js/2.fa83f41b.chunk.js:2:793221)
    at Ui (https://www.iobroker.net/static/js/2.fa83f41b.chunk.js:2:793156)
```

**Comment by Apollon77** [comment]
It also had the brackets around the email ... 

I proposed at least a fix as temp workaround
